services:
  rocketchat:
    extends:
      file: ${SERVICE_ROCKETCHAT_YML_ENV}
      service: rocketchat
    environment:
      - VIRTUAL_HOST=${CONTEXT_DOMAINS}
      - LETSENCRYPT_HOST=${CONTEXT_DOMAINS}
      - LETSENCRYPT_EMAIL=${CONTEXT_EMAIL}
      - ROOT_URL=http://${DOMAIN_MAIN}