services:
  rocketchat:
    extends:
      file: ${RUNTIME_SERVICE_ROCKETCHAT_YML_ENV}
      service: rocketchat
    environment:
      - VIRTUAL_HOST=${RUNTIME_DOMAINS}
      - LETSENCRYPT_HOST=${RUNTIME_DOMAINS}
      - LETSENCRYPT_EMAIL=${RUNTIME_EMAIL}
      - ROOT_URL=http://${RUNTIME_DOMAIN_MAIN}