services:
  wex_dev:
    container_name: wex_local_dev
    image: wexample/wex:dev
    privileged: true
    extends:
        file: ${WEX_COMPOSE_YML_DEFAULT}
        service: default
    build:
      context: ${APP_PATH_ROOT}
      dockerfile: ./.wex/docker/Dockerfile.dev
    volumes:
      # Mount wex outside the apps list
      - ${APP_PATH_ROOT}:/opt/wex
      # Source repo before build
      - ${APP_PATH_ROOT}source:/var/www/source
      # Use GPG key for package signature
      - ${APP_PATH_ROOT}gpg/:/root/.gnupg

