services:
  wex_dev:
    container_name: wex_local_dev
    image: wexample/wex:dev
    privileged: true
    extends:
        file: ${SERVICE_DEFAULT_YML_ENV}
        service: default
    build:
      context: ${CONTEXT_DIR}
      dockerfile: ./.wex/docker/Dockerfile.dev
    volumes:
      # Mount wex outside the apps list
      - ${CONTEXT_DIR}:/opt/wex
      # Mount apps
      - /var/www/${CONTEXT_ENV}:/var/www/html
      # Authorize app to reuse ssh authentications
      - ${SSH_AUTH_SOCK}:/ssh-agent
      # Allow to run docker from inside container
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
