FROM python:3.12.0a6-bullseye

# Prepare install, not really part of the install commands
RUN apt update && apt install sudo -y

# Install dependencies
RUN sudo apt install gnupg2 wget -y \
  && sudo wget -O - https://apt.wexample.com/gpg | sudo apt-key add - \
  && echo "deb http://apt.wexample.com/ beta main" | sudo tee /etc/apt/sources.list.d/wexample.list \
  && sudo apt-get update \
  && sudo apt install wex