version: '3.9'

services:
  wex_dev:
    container_name: wex_local_dev
    image: wexample/wex:dev
    privileged: true
    extends:
        file: ${WEX_COMPOSE_YML_DEFAULT}
        service: default
    build:
      context: ${APP_PATH_ROOT}
      dockerfile: ./.wex/docker/Dockerfile.dev
    volumes:
      - ${APP_PATH_ROOT}:/var/www/html