services:
  wex_dev:
    container_name: wex_local_dev
    image: gitlab-docker.wexample.com/wexample/wex/dev:latest
    privileged: true
    extends:
        file: ${WEX_COMPOSE_YML_DEFAULT}
        service: default
    volumes:
      # Mount wex outside the apps list
      - ${APP_PATH_ROOT}:/var/www/
      # Source repo before build, override to support symlink.
      - ${APP_PATH_ROOT}source:/var/www/source
      # Use GPG key for package signature
      - ${APP_PATH_ROOT}gpg/:/root/.gnupg

