 # Use this file to run and test application
 # using a standard docker composer command :
 # docker compose -f .wex/docker/docker-compose.test-remote.yml up -d
services:
  wex_test_remote:
    container_name: wex_test_remote
    image: gitlab-docker.wexample.com/wexample/wex/test-remote
    restart: unless-stopped
    stdin_open: true
    tty: true
    # When tests runs in a container, as in deployment pipeline,
    # we should ensure the remote is in the same network as current one.
    network_mode: bridge
