services:
  wex_dev:
    container_name: wex_${RUNTIME_ENV}_dev
    image: gitlab-docker.wexample.com/wexample-public/docker/wex:dev
    privileged: true
    extends:
      file: ${RUNTIME_SERVICE_DEFAULT_YML_BASE}
      service: default
    ports:
      # Webhooks listening port
      - 4242:4242
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      # Mount wex outside the apps list
      - ${RUNTIME_PATH_APP}:/opt/wex
      # Mount apps
      - /var/www/${RUNTIME_ENV}:/var/www/${RUNTIME_ENV}
      # Authorize app to reuse ssh authentications (i.e.: git operations)
      - ${WEX_RUNNER_SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
      # Allow to run docker from inside container
      - /var/run/docker.sock:/var/run/docker.sock
      # For debug purposes
      - ${RUNTIME_PATH_APP}tmp/wex-proxy:/var/www/local/wex-proxy
