FROM python:3.12.0a6-bullseye

# Create a username for pid 1000
# which is the default pid given by Docker
RUN useradd --uid 1000 owner

# Ruby is required for changelog generator
RUN apt-get update && apt-get install -y \
  ruby-full \
  sudo

# Install Ruby packages
RUN gem install github_changelog_generator

# Need last version for compatibility with python module
RUN apt-get upgrade git -y

RUN pip install \
  click \
  pip-tools \
  pytest
