FROM alpine:latest

RUN apk --no-cache add openssh
RUN ssh-keygen -A
RUN echo 'root:TEST_PASSWORD' | chpasswd

# Configurer SSHD
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
RUN echo "PermitEmptyPasswords no" >> /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
