 # Use this file to run and test application
 # using a standard docker composer command :
 # docker compose -f .wex/docker/docker-compose.test-remote.yml up -d
services:
  wex_test_remote:
    container_name: wex_test_remote
    image: gitlab-docker.wexample.com/wexample/wex/test-remote
    restart: unless-stopped
    stdin_open: true
    tty: true
    # When tests runs in a container, as in deployment pipeline,
    # we should ensure the remote is in the same network as current one.
    network_mode: bridge
    command: bash /usr/lib/wex/.wex/docker/test_remote-entrypoint.sh
    volumes:
      - ../../:/usr/lib/wex
      # Allow container to override env data
      - ../.env.test_remote:/usr/lib/wex/.wex/.env
      - /usr/lib/wex/.wex/python/venv
      - /usr/lib/wex/tmp
      # Docker sharing
      - /var/run/docker.sock:/var/run/docker.sock
      # Share whole dir as test will create several environments
      - /var/www:/var/www