stages:
  - diagnose

diagnose-docker:
  stage: diagnose
  image: docker:25.0.3
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Runner info:"
    - whoami || true
    - id || true
    - uname -a || true
    - echo "Groups:" && groups || true
    - echo "Docker binary:" && command -v docker || true
    - echo "Docker version:" && docker version || true
    - echo "Docker info:" && docker info || true
    - echo "Socket perms:" && ls -l /var/run/docker.sock || true
    - echo "Docker ps:" && docker ps || true
    - echo "Env subset:" && env | grep -E '^(CI_|DOCKER|CI_REGISTRY)' || true
  allow_failure: true
  when: on_success