stages:
  - setup
  - test
  - deploy

setup:app:
  stage: setup
  only:
    - master
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script:
    - wex && [[ "$(wex hi)" = "hi!" ]] && wex default::core/uninstall || true
    - sudo git clone https://github.com/wexample/wex.git /opt/wex && sudo bash /opt/wex/install

test:app:
  stage: test
  only:
    - master
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script:
    - sudo wex core/version
    - sudo wex core/update
    - sudo wex test
    # Little check the job was executed to the end
    - echo "The end"

deploy:app:
  stage: deploy
  only:
    - master
  script:
    - sudo wex core/push -o=github
  needs:
    - job: test:app
      artifacts: true