stages:
  - deploy

deploy:
  stage: deploy
  script:
    # Stop running container
    - docker stop wex_build 2>/dev/null && docker rm wex_build 2>/dev/null || true
    # Create or empty temp build folder
    - mkdir -p /home/gitlab-runner/builds/ && rm -rf /home/gitlab-runner/builds//* /home/gitlab-runner/builds//.[!.]* || true
    # Create a copy of current git repo
    - cp -r .git /home/gitlab-runner/builds/
    # Go to build folder
    - cd /home/gitlab-runner/builds/
    # Checkout build branch
    - git fetch && git checkout build
    # Run container
    - docker compose -f .wex/docker/docker-compose.ci.yml up -d
