stages:
  - test

variables:
  MAIN_BRANCH_NAME: "master"

include:
#  - remote: 'https://gitlab.wexample.com/wexample-public/ci-cd/-/raw/main/.gitlab-ci.build-image.yml'
  - remote: 'https://gitlab.wexample.com/wexample-public/ci-cd/-/raw/main/.gitlab-ci.checkup.yml'

.docker_login:
  script:
    # Display the registry we are connecting to, taking into account whether a port is specified.
    - echo "Connecting to $CI_REGISTRY$CI_REGISTRY_PORT_WITH_COLON"
    # Log into the Docker registry, accounting for sudo and daemon availability.
    - |
      set -e
      DOCKER_CLI="docker"
      # Try plain docker first
      if ! docker info >/dev/null 2>&1; then
        # Try with sudo if available (non-interactive)
        if command -v sudo >/dev/null 2>&1; then
          DOCKER_CLI="sudo -n docker"
        fi
      fi
      if $DOCKER_CLI info >/dev/null 2>&1; then
        echo "$CI_REGISTRY_PASSWORD" | $DOCKER_CLI login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY$CI_REGISTRY_PORT_WITH_COLON"
      else
        echo "Docker daemon not accessible, skipping docker login"
      fi

# Rules when branch has been merged.
.merge_branch_rules: &merge-branch-master-rules
  - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $MAIN_BRANCH_NAME'

.merge_to_master:
  resource_group: main_pipeline
  rules:
    - *merge-branch-master-rules

.on_master:
  resource_group: main_pipeline
  only:
    - master

.build_live_image:
  extends: [ .merge_to_master, .globals, .docker_login, .build_image_app ]
  script:
    - !reference [ .docker_login, script ]
    - !reference [ .build_image_app, script ]

.test_cleanup:
  script:
    - docker ps -q --filter name=test_app_ | xargs -r docker rm -f
    - docker ps -q --filter name=wex_proxy_test_ | xargs -r docker rm -f
    - rm -rf /var/www/test
    - rm -rf /var/www/test_*

# Use this into test job to use last repo,
# instead of rebuilding "rc" image.
.test_rescue:
  script:
    - rm -rf /opt/wex
    - cp -r . /opt/wex
    - bash /opt/wex/cli/install

test:
  stage: test
  image: gitlab-docker.wexample.com/wexample/wex/rc:latest
  extends: [ .merge_to_master, .test_cleanup, .test_rescue, .docker_login ]
  variables:
    GIT_STRATEGY: none
  script:
    - !reference [ .test_cleanup, script ]
    - !reference [ .docker_login, script ]
    # Change environment
    - sudo wex app::env/set --app-dir /opt/wex/ -e test
    - sudo wex rebuild
    # Run tests, as "owner", with sudo.
    - sudo -u owner sudo wex test -vvv
    - !reference [.test_cleanup, script]