stages:
#  - checkup_pipeline
#  - build_pipeline_images
#  - checkup_builds
#  - test
  - deploy
  - checkup_install
  - build_docker

variables:
  MAIN_BRANCH_NAME: "master"

include:
#  - local: '.gitlab-ci.stage.checkup-pipeline.yml'
#  - local: '.gitlab-ci.stage.build-pipeline-images.yml'
#  - local: '.gitlab-ci.stage.checkup-builds.yml'
#  - local: '.gitlab-ci.stage.test.yml'
  - local: '.gitlab-ci.stage.deploy.yml'
  - local: '.gitlab-ci.stage.checkup-install.yml'

# Rebuild public image
build_docker:
  stage: build_docker
  only:
    - master
  needs:
    - checkup-install:debian
    - checkup-install:ubuntu:22
  trigger:
    project: wexample-public/docker
    branch: main