stages:
  - setup
  - test
  - merge

variables:
  GIT_SUBMODULE_STRATEGY: recursive

setup:
  stage: setup
  only:
    - merge_requests
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script:
      # Remove old version.
    - wex && [[ "$(wex hi)" = "hi!" ]] && sudo wex default::core/uninstall || true
      # Clone from local build folder.
    - sudo cp -R "${CI_PROJECT_DIR}" /opt/wex && sudo bash /opt/wex/install

test:
  stage: test
  only:
    - merge_requests
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script:
    - sudo wex test
  needs:
    - job: setup