include:
  - project: 'wexample-public/ci-cd'
    ref: main
    file: '.gitlab-ci.checkup.yml'

checkup_builds:remote:
  stage: checkup_builds
  extends: [ .merge_rule_to_main_branch ]
  image: gitlab-docker.wexample.com/wexample/wex/test-remote:latest
  needs:
    - job: build_pipeline_image_test_remote
      optional: true
  script:
    - wex hi
    - wex version
    - cat /opt/wex/.wex/docker/test_remote/test_remote-entrypoint.sh

.checkup_sources:
  resource_group: main_pipeline
  stage: checkup_builds
  extends: [ .merge_rule_to_main_branch, .checkup_fails_if_non_committed ]
  image: gitlab-docker.wexample.com/wexample/wex/rc:latest
  needs:
    - job: checkup_pipeline_image_remote
      optional: true
  variables:
    GIT_STRATEGY: none
  before_script:
    - cd /opt/wex
    - source .wex/python/venv/bin/activate
    - pip install -r requirements-dev.txt
    - touch .wex/.env # Need a fake file to not warn if missing

checkup_builds:code:
  extends: [ .checkup_sources ]
  script:
    - wex .code/check

checkup_builds:format:
  extends: [ .checkup_sources ]
  script:
    - wex .code/format