stages:
#  - setup
#  - test
  - merge_addons

variables:
  GIT_SUBMODULE_STRATEGY: recursive

#setup:
#  stage: setup
##  rules:
##    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
#  variables:
#    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
#    TERM: dumb
#  script:
#      # Remove old version.
#    - wex && [[ "$(wex hi)" = "hi!" ]] && sudo wex default::core/uninstall || true
#      # Clone from local build folder.
#    - sudo cp -R "${CI_PROJECT_DIR}" /opt/wex && sudo bash /opt/wex/install

#test:
#  stage: test
##  rules:
##    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
#  variables:
#    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
#    TERM: dumb
#  script:
#    - sudo wex test
#  needs:
#    - job: setup

merge_addons:
  stage: merge_addons
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master"'
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script: |
      for ADDON in $(ls ./addons); do
        if [ -d "${WEX_DIR_ADDONS}${ADDON}" ]; then
          _wexLog "Changing origin for ${ADDON}..."
          git -C "./addons/$ADDON" config remote.origin.url ssh://git@gitlab.wexample.com:4567/wexample/wex-addon-$ADDON.git;

          _wexLog "Pushing ${ADDON}..."
          sudo -u gitlab-runner -H sh -c "\
            cd ${WEX_DIR_ADDONS}${ADDON} && \
            git checkout master && \
            git merge --no-ff develop && \
            git push origin master"
        fi
      done
#  needs:
#    - job: test