stages:
  - test
  - build
  - deploy
  - test_apt_install

test:
  stage: test
  image: gitlab-docker.wexample.com/wexample-public/docker/debian
#  only:
#    - tags
  script:
    # Stops script on failure
    - set -e
    # We install manually as apt package does not exist at this point
    - apt update
    - apt install procps python3-pip sudo -y
    # Install
    - sudo bash ./cli/install
    # Create env file
    - echo "APP_ENV=dev" > ".wex/.env"
    # Test
    - sudo bash ./cli/wex test

build:
  stage: build
#  only:
#    - tags
  needs:
    - test
  script:
    # TODO TMP
    - ls -la
#    - BUILD_VERSION=$(cat version.txt)
#    # Stop running container
#    - docker stop wex_build 2>/dev/null && docker rm wex_build 2>/dev/null || true
#    # Create or empty temp build folder
#    - mkdir -p /home/gitlab-runner/builds/wex && rm -rf /home/gitlab-runner/builds/wex/* /home/gitlab-runner/builds/wex/.[!.]* || true
#    # Create a copy of current git repo
#    - cp -r .git /home/gitlab-runner/builds/wex
#    # Go to build folder
#    - cd /home/gitlab-runner/builds/wex
#    # Checkout build branch
#    - git fetch && git checkout build
#    - git checkout .wex/*
#    - git clean -fd
#    - git reset --hard origin/build
#    # Create link to source
#    - ln -s ${CI_PROJECT_DIR} source
#    # Run container
#    - docker compose -f .wex/docker/docker-compose.ci.yml --env-file .wex/docker/.ci.env build --no-cache
#    - docker compose -f .wex/docker/docker-compose.ci.yml --env-file .wex/docker/.ci.env up -d
#    # Run build
#    - docker exec wex_build /bin/bash -c "sudo python3 /var/www/script/build.py -n wex -gid ${CI_PROJECT_ID} -gtk '${WEX_BUILD_TOKEN}' -v '${BUILD_VERSION}'"

deploy:
  stage: deploy
#  only:
#    - tags
  needs:
    - build
  script:
    # TODO TMP
    - ls -la
#    - BUILD_VERSION=$(cat version.txt)
#    # Ask apt repo to publish release
#    - curl "http://wexample.com:4242/webhook/wex-apt-repo/publish?p=${CI_PROJECT_ID}&v=${BUILD_VERSION}"


# Try to install using the new debian apt repository.
test_apt_install:
  stage: test_apt_install
  image: gitlab-docker.wexample.com/wexample-public/docker/debian
#  only:
#    - tags
  needs:
    - deploy
  script:
      # Stops script on failure
    - set -e
    - apt update
    - apt install gnupg2 wget -y
    - wget -O - https://apt.wexample.com/gpg | apt-key add -
    - echo "deb http://apt.wexample.com/ beta main" | tee /etc/apt/sources.list.d/wexample.list
    - apt-get update
    - apt install wex -y

