stages:
  - build_apt
  - deploy
  - checkup_install

.on_master:
  only:
    - master

build_apt:
  stage: build_apt
  image: gitlab-docker.wexample.com/wexample/wex/wex-build:build
  extends: [ .on_master ]
  script:
    - BUILD_VERSION=$(cat version.txt)
    - mkdir -p /var/tmp/build
    - cp -r .git /var/tmp/build
    - cd /var/tmp/build
    - git fetch && git checkout build
    - ln -s ${CI_PROJECT_DIR} source
    - sudo python3 /var/tmp/build/script/build.py -n wex -gid ${CI_PROJECT_ID} -gtk ${WEX_BUILD_TOKEN} -v ${BUILD_VERSION}

deploy:
  stage: deploy
  image: curlimages/curl
  extends: [ .on_master ]
  needs:
    - build_apt
  script:
    - BUILD_VERSION=$(cat version.txt)
    - curl --fail "http://151.80.23.108:6543/webhook/app/prod/wex-apt-repo/apt/publish?_token=${WEX_WEBHOOK_TOKEN}&project=${CI_PROJECT_ID}&version=${BUILD_VERSION}"

.checkup_install:
  extends: [ .on_master ]
  needs:
    - deploy
  script:
    - set -e
    - apt-get update -qq
    - apt-get install -y gnupg2 wget
    - wget -O - https://apt.wexample.com/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/wexample.gpg
    - echo "deb http://apt.wexample.com/ stable main" | tee /etc/apt/sources.list.d/wexample.list
    - apt-get update -qq
    - apt-get install -y wex
    - wex hi
    - BUILD_VERSION=$(cat version.txt)
    - INSTALLED_VERSION=$(wex version)
    - echo "Expected ${BUILD_VERSION}, got ${INSTALLED_VERSION}"
    - test "${BUILD_VERSION}" = "${INSTALLED_VERSION}"
    - apt-get remove -y wex

checkup_install_debian:
  extends: .checkup_install
  stage: checkup_install
  image: debian:bookworm

checkup_install_ubuntu:
  extends: .checkup_install
  stage: checkup_install
  image: ubuntu:24.04

