stages:
  - test
  - build
  - deploy
  - test_apt_install

test:
  stage: test
  image: gitlab-docker.wexample.com/wexample-public/docker/wex:test
  services:
    # Match the version number with image internal docker service.
    - name: docker:24.0.6-dind
  before_script:
    # Start Docker daemon manually and display logs
    - dockerd &> docker.log &
    - sleep 30  # Give it some time to start
    - cat docker.log
    # Added a timeout to ensure that the loop does not run indefinitely
    - timeout=30; while [ $timeout -gt 0 ] && ! docker info; do echo 'Waiting for Docker service to start'; sleep 1; timeout=$((timeout - 1)); done; if [ $timeout -eq 0 ]; then echo "Docker service did not start on time"; exit 1; fi
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: vfs
  only:
    - tags
  script:
    # Check docker exists
    - docker --version
    # Stops script on failure
    - set -e
    # We install manually as apt package does not exist at this point
    - apt update
    # Install minimum packages to launch install script
    - apt install sudo -y
    # Install
    - sudo bash ./cli/install
    # Fake local app
    - mkdir -p /var/www/test
    - ln -s $(realpath .) "/var/www/test/wex"
    # Create env file
    - echo "APP_ENV=test" > ".wex/.env"
    # Create a new user named "owner"
    - sudo useradd -m owner
    # Add the user to the sudoers file to allow password-less sudo
    - echo "owner ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
    # Run wex test as owner with sudo
    - sudo su - owner -c "sudo wex test"
    # Uninstall
    - sudo bash ./cli/uninstall

build:
  stage: build
  image: gitlab-docker.wexample.com/wexample-public/docker/wex:build
  only:
    - tags
  needs:
    - test
  script:
    - BUILD_VERSION=$(cat version.txt)
    # Create build folder
    - mkdir -p /var/www/build
    # Create a copy of current git repo
    - cp -r .git /var/www/build
    # Go to build folder
    - cd /var/www/build
    # Checkout build branch
    - git fetch && git checkout build
    # Create link to source
    - ln -s ${CI_PROJECT_DIR} source
    # Build
    - sudo python3 /var/www/build/script/build.py -n wex -gid ${CI_PROJECT_ID} -gtk ${WEX_BUILD_TOKEN} -v ${BUILD_VERSION}

deploy:
  stage: deploy
  only:
    - tags
  needs:
    - build
  script:
    - BUILD_VERSION=$(cat version.txt)
    # Ask apt repo to publish release
    - curl "http://wexample.com:4242/webhook/wex-apt-repo/publish?p=${CI_PROJECT_ID}&v=${BUILD_VERSION}"

# Try to install using the new debian apt repository.
test_apt_install:
  stage: test_apt_install
  image: gitlab-docker.wexample.com/wexample-public/docker/debian
  only:
    - tags
  needs:
    - deploy
  script:
    # Stops script on failure
    - set -e
    - apt update
    - apt install gnupg2 wget -y
    - wget -O - https://apt.wexample.com/gpg | apt-key add -
    - echo "deb http://apt.wexample.com/ beta main" | tee /etc/apt/sources.list.d/wexample.list
    - apt update
    - apt install wex -y
    - wex hi
    - apt remove wex -y
