stages:
  - test
  - build
  - deploy
  - test_apt_install

test:
  stage: test
  image: gitlab-docker.wexample.com/wexample-public/docker/debian
  only:
    - tags
  script:
    # Stops script on failure
    - set -e
    # We install manually as apt package does not exist at this point
    - apt update
    - apt install procps python3-pip sudo -y
    # Install
    - sudo bash ./cli/install
    # Fake local app
    - mkdir -p /var/www/dev
    - ln -s $(realpath .) "/var/www/dev/wex"
    # Create env file
    - echo "APP_ENV=dev" > ".wex/.env"
    # Test
    - sudo bash ./cli/wex test
    # Uninstall
    - sudo bash ./cli/uninstall

build:
  stage: build
  image: gitlab-docker.wexample.com/wexample-public/docker/wex:dev
  only:
    - tags
  needs:
    - test
  script:
    - BUILD_VERSION=$(cat version.txt)
    # Create build folder
    - mkdir -p /var/www/build
    # Create a copy of current git repo
    - cp -r .git /var/www/build
    # Go to build folder
    - cd /var/www/build
    # Checkout build branch
    - git fetch && git checkout build
    # Create link to source
    - ln -s ${CI_PROJECT_DIR} source
    # Build
    - sudo python3 /var/www/build/script/build.py -n wex -gid ${CI_PROJECT_ID} -gtk ${WEX_BUILD_TOKEN} -v ${BUILD_VERSION}

deploy:
  stage: deploy
  only:
    - tags
  needs:
    - build
  script:
    - BUILD_VERSION=$(cat version.txt)
    # Ask apt repo to publish release
    - curl "http://wexample.com:4242/webhook/wex-apt-repo/publish?p=${CI_PROJECT_ID}&v=${BUILD_VERSION}"

# Try to install using the new debian apt repository.
test_apt_install:
  stage: test_apt_install
  image: gitlab-docker.wexample.com/wexample-public/docker/debian
  only:
    - tags
  needs:
    - deploy
  script:
    # Stops script on failure
    - set -e
    - apt update
    - apt install gnupg2 wget -y
    - wget -O - https://apt.wexample.com/gpg | apt-key add -
    - echo "deb http://apt.wexample.com/ beta main" | tee /etc/apt/sources.list.d/wexample.list
    - apt update
    - apt install wex -y
    - wex hi
    - apt uninstall wex -y
