stages:
  - test

.test_cleanup:
  script:
    - docker ps -q --filter name=test_app_ | xargs -r docker rm -f
    - docker ps -q --filter name=wex_proxy_test_ | xargs -r docker rm -f
    - rm -rf /var/www/test
    - rm -rf /var/www/test_*

.test_rescue:
  script:
    - rm -rf /opt/wex
    - cp -r . /opt/wex
    - bash /opt/wex/cli/install

test:
  stage: test
  image: gitlab-docker.wexample.com/wexample/wex/rc:latest

  services:
    - name: docker:dind
      command: ["--tls=false"]

  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

  script:
    - !reference [.test_cleanup, script]
    - !reference [.test_rescue, script]
    - sudo wex app::env/set --app-dir /opt/wex/ -e test
    - sudo wex rebuild
    - sudo -u owner sudo wex test -vvv
    - !reference [.test_cleanup, script]