stages:
  - build_image_wex_dev

variables:
  DOCKER_DRIVER: overlay2

build_image_wex_dev:
  stage: build_image_wex_dev
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -f .wex/docker/Dockerfile.dev -t wex/dev:latest -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - changes:
        - .wex/docker/Dockerfile.dev
