stages:
  - build

include:
  - project: 'wexample-public/ci-cd'
    ref: main
    file: '.gitlab-ci.docker.yml'

build:wex-build:build:
  stage: build
  extends: [.docker_build_image_file]
  variables:
    IMAGE_NAME: wex-build
    IMAGE_TAG: build
    IMAGE_DOCKERFILE: .wex/docker/Dockerfile.build
    IMAGE_BUILD_CONTEXT: .wex/docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "pipeline"'
    - when: never
