stages:
  - deploy

test:app:
  stage: deploy
  only:
    - master
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script:
    - sudo wex core/version
    - sudo wex core/update
    - sudo wex test
    # Little check the job was executed to the end
    - echo "The end"
