stages:
  - setup
  - test
  - merge_addons
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

setup:
  stage: setup
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script:
      # Remove old version.
    - wex && [[ "$(wex hi)" = "hi!" ]] && sudo wex default::core/uninstall || true
      # Clone from local build folder.
    - sudo cp -R "${CI_PROJECT_DIR}" /opt/wex && sudo bash /opt/wex/install

test:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script:
    - sudo wex test
  needs:
    - setup

merge_addons:
  stage: merge_addons
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script: sudo wex addons/deploy
  needs:
    - test

deploy:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  needs:
    - merge_addons
  image: curlimages/curl
  script:
    - curl -X GET https://wex:cdsnkcjnsdhcdbshqcbdscbqksdbchkqfvbh@n8n.wexample.com/webhook/3924f3d2-37a4-4c79-b68e-4cc90fa244a6?v=$(wex default::core/version)
