stages:
  - setup
  - test
  - deploy

setup:
  stage: setup
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script: |
    # Remove old version.
    wex && [[ "$(wex hi)" = "hi!" ]] && sudo wex default::core/uninstall || true
    # Clone from local build folder.
    sudo git clone "${CI_PROJECT_DIR}/.git/" /opt/wex && sudo bash /opt/wex/install
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && "$(git log --format=%B -n 1 $CI_COMMIT_SHA)" == "New version"'

test:
  stage: test
  variables:
    # To avoid 'tput: unknown terminal "unknown"' in gitlab-ci console log
    TERM: dumb
  script:
    - sudo wex test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && "$(git log --format=%B -n 1 $CI_COMMIT_SHA)" == "New version"'
  needs:
    - job: setup

deploy:
  stage: deploy
  script:
    - sudo wex core/push -o=github
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && "$(git log --format=%B -n 1 $CI_COMMIT_SHA)" == "New version"'
  needs:
    - job: test
