stages:
  - deploy

deploy:
  stage: deploy
  script:
    # Stop running container
    - docker stop wex_build 2>/dev/null && docker rm wex_build 2>/dev/null || true
    # Create or empty temp build folder
    - mkdir -p /home/gitlab-runner/builds/wex && rm -rf /home/gitlab-runner/builds/wex/* /home/gitlab-runner/builds/wex/.[!.]* || true
    # Create a copy of current git repo
    - cp -r .git /home/gitlab-runner/builds/wex
    # Go to build folder
    - cd /home/gitlab-runner/builds/wex
    # Checkout build branch
    - git fetch && git checkout build
    # Run container
    #- docker compose -f .wex/docker/docker-compose.ci.yml up -d
