stages:
  - deploy

deploy:
  stage: deploy
  script:
    - BUILD_VERSION=$(cat version.txt)
    # Stop running container
    - docker stop wex_build 2>/dev/null && docker rm wex_build 2>/dev/null || true
    # Create or empty temp build folder
    - mkdir -p /home/gitlab-runner/builds/wex && rm -rf /home/gitlab-runner/builds/wex/* /home/gitlab-runner/builds/wex/.[!.]* || true
    # Create a copy of current git repo
    - cp -r .git /home/gitlab-runner/builds/wex
    # Go to build folder
    - cd /home/gitlab-runner/builds/wex
    # Checkout build branch
    - git fetch && git checkout build
    - git checkout .wex/*
    - git clean -fd
    - git reset --hard origin/build
    # Run container
    - docker compose -f .wex/docker/docker-compose.ci.yml up -d
    # Run build
    - docker exec -ti /bin/sh -c "sudo python3 /var/www/script/build.py -n wex -gid 155 -gtk 'glpat-PAHuLocqyf1ZGuY58GYb' -v '${BUILD_VERSION}'"
