stages:
  - test

.test_cleanup:
  script:
    - |
      if docker -H "${DOCKER_HOST:-unix:///var/run/docker.sock}" info >/dev/null 2>&1; then
        docker -H "${DOCKER_HOST:-unix:///var/run/docker.sock}" ps -q --filter name=test_app_ | xargs -r -I {} docker -H "${DOCKER_HOST:-unix:///var/run/docker.sock}" rm -f {}
        docker -H "${DOCKER_HOST:-unix:///var/run/docker.sock}" ps -q --filter name=wex_proxy_test_ | xargs -r -I {} docker -H "${DOCKER_HOST:-unix:///var/run/docker.sock}" rm -f {}
      else
        echo "Docker daemon not accessible, skipping container cleanup"
      fi
    - rm -rf /var/www/test
    - rm -rf /var/www/test_*

.test_rescue:
  script:
    - rm -rf /opt/wex
    - cp -r . /opt/wex
    - bash /opt/wex/cli/install

test:
  stage: test
  image: gitlab-docker.wexample.com/wexample/wex/rc:latest
  variables:
    GIT_STRATEGY: none
    DOCKER_DRIVER: overlay2
  script:
    - !reference [.test_cleanup, script]
    - !reference [.test_rescue, script]
    - sudo wex app::env/set --app-dir /opt/wex/ -e test
    - sudo wex rebuild
    - sudo -u owner sudo wex test -vvv
    - !reference [.test_cleanup, script]