#!/usr/bin/env bash

GLOBAL_COMMAND=wex

echo "Changing permissions..."
chmod +x main.py

echo "Creating global command..."
SCRIPT="index.py"
LINK="/usr/local/bin/${GLOBAL_COMMAND}"
if [ -e $LINK ]; then
    sudo rm $LINK
fi

sudo ln -s $(realpath ${SCRIPT}) ${LINK}