services:
    gitlab:
      container_name: ${RUNTIME_NAME}_gitlab
      image: gitlab/gitlab-ce:16.4.1-ce.0
      hostname: ${RUNTIME_DOMAIN_MAIN}
      ports:
        - '4567:22'
      volumes:
        - ${RUNTIME_PATH_APP}backups:/var/opt/gitlab/backups
        - ${RUNTIME_PATH_APP}config:/etc/gitlab
        - ${RUNTIME_PATH_APP}logs:/var/log/gitlab
        - ${RUNTIME_PATH_APP}data:/var/opt/gitlab
      environment:
        - VIRTUAL_HOST=${RUNTIME_DOMAINS_STRING}
        - SMTP_DOMAIN=${RUNTIME_DOMAIN_MAIN}
        - VIRTUAL_PORT=80
        - GITLAB_SHELL_SSH_PORT=4567
      extends:
          file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
          service: default