services:
    phpmyadmin:
        container_name: '${RUNTIME_NAME}_phpmyadmin'
        image: phpmyadmin/phpmyadmin:5.2
        environment:
          - LETSENCRYPT_EMAIL=${RUNTIME_EMAIL}
          - LETSENCRYPT_HOST=${RUNTIME_DOMAIN_PMA}
          - PMA_HOST=${DB_MAIN_HOST}
          - PMA_PORT=${DB_MAIN_PORT}
          - VIRTUAL_HOST=${RUNTIME_DOMAIN_PMA}
          - PMA_USER=${DB_MAIN_USER}
          - PMA_PASSWORD=${DB_MAIN_PASSWORD}
        extends:
            file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
            service: default
        profiles:
          - env_dev
          - env_local
