services:
    phpmyadmin:
        container_name: ${RUNTIME_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin:5.2
        environment:
          - LETSENCRYPT_EMAIL=${RUNTIME_EMAIL}
          - LETSENCRYPT_HOST=${RUNTIME_DOMAIN_PMA}
          - VIRTUAL_HOST=${RUNTIME_DOMAIN_PMA}
          - PMA_HOST=${RUNTIME_SERVICE_PHPMYADMIN_DB_HOST}
          - PMA_PORT=${RUNTIME_SERVICE_PHPMYADMIN_DB_PORT}
        extends:
            file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
            service: default
