services:
  matomo:
    container_name: '${CONTEXT_NAME}_matomo'
    image: 'matomo:${MATOMO_VERSION}'
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${CONTEXT_DOMAINS}
      - VIRTUAL_PORT=80
      # Database
      - MATOMO_DATABASE_HOST=${MYSQL_DB_HOST}
      - MATOMO_DATABASE_DBNAME=${MYSQL_DB_NAME}
      - MATOMO_DATABASE_USERNAME=${MYSQL_DB_USER}
      - MATOMO_DATABASE_PASSWORD=${MYSQL_DB_PASSWORD}
    volumes:
      - ${CONTEXT_DIR}data:/var/www/html
    extends:
        file: ${SERVICE_DEFAULT_YML_ENV}
        service: default
