services:
    php:
        container_name: ${RUNTIME_NAME}_php
        image: wexample/php-8.2:latest
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=${RUNTIME_DOMAINS_STRING}
            - VIRTUAL_PORT=80
        volumes:
            # Security ! Hide sensitive data containing passwords and databases !
            - /var/www/html/.git
            - /var/www/html/.wex
            # Mysql dumps
            - ${RUNTIME_PATH_APP_ENV}mysql/dumps:/var/www/mysql/dumps
            # Cron management
            - ${RUNTIME_PATH_APP_ENV}cron/${RUNTIME_ENV}:/var/default.cron
        extends:
            file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
            service: default
