services:
  matomo:
    container_name: ${RUNTIME_NAME}_matomo
    image: matomo:4.15.1-apache
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${RUNTIME_DOMAINS_STRING}
      - VIRTUAL_PORT=80
      # Database
      - MATOMO_DATABASE_HOST=${SERVICE_MYSQL_HOST}
      - MATOMO_DATABASE_DBNAME=${SERVICE_MYSQL_NAME}
      - MATOMO_DATABASE_USERNAME=${SERVICE_MYSQL_USER}
      - MATOMO_DATABASE_PASSWORD=${SERVICE_MYSQL_PASSWORD}
    volumes:
      - ${RUNTIME_PATH_APP}data:/var/www/html
    extends:
        file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
        service: default
