services:
    wordpress:
        container_name: '${RUNTIME_NAME}_wordpress'
        image: wordpress:6.3.1-php8.2-apache
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=${RUNTIME_DOMAINS_STRING}
            - VIRTUAL_PORT=80
            # Database
#            - WORDPRESS_DB_HOST=${MYSQL_DB_HOST}
#            - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
#            - WORDPRESS_DB_USER=${MYSQL_DB_USER}
#            - WORDPRESS_DB_PASSWORD=${MYSQL_DB_PASSWORD}
#            - WORDPRESS_TABLE_PREFIX=${WP_DB_TABLE_PREFIX}
            #- WORDPRESS_DEBUG=1
            #- WORDPRESS_CONFIG_EXTRA=
        volumes:
            # Wordpress
            - ${RUNTIME_PATH_APP}:/var/www/html
            # Security ! Hide and .wex data containing passwords and databases !
            - /var/www/html/.wex
        extends:
            file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
            service: default

    # From : https://stackoverflow.com/a/51001043
    cli:
        container_name: '${RUNTIME_NAME}_cli'
        image: wordpress:cli-2.7.1-php8.2
#        environment:
            # Database
#            - WORDPRESS_DB_HOST=${MYSQL_DB_HOST}
#            - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
#            - WORDPRESS_DB_USER=${MYSQL_DB_USER}
#            - WORDPRESS_DB_PASSWORD=${MYSQL_DB_PASSWORD}
#            - WORDPRESS_TABLE_PREFIX=${WP_DB_TABLE_PREFIX}
        volumes:
            # Wordpress
            - ${RUNTIME_PATH_APP}:/var/www/html
            # Security ! Hide and .wex data containing passwords and databases !
            - /var/www/html/.wex
            - ${RUNTIME_PATH_APP_WEX}wp-cli/:/.wp-cli/
        extends:
            file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
            service: default
