import logging

from src.const.globals import COLOR_BLUE, COLOR_GRAY, COLOR_RED, COLOR_YELLOW

ERR_ARGUMENT_COMMAND_MALFORMED = "ERR_ARGUMENT_COMMAND_MALFORMED"
ERR_COMMAND_FILE_NOT_FOUND = "ERR_COMMAND_FILE_NOT_FOUND"
ERR_TEST = "ERR_TEST"

COLORS = {
    logging.DEBUG: COLOR_GRAY,
    logging.INFO: COLOR_BLUE,
    logging.WARN: COLOR_YELLOW,
    logging.ERROR: COLOR_RED,
    logging.CRITICAL: COLOR_RED,
}
