ERR_ARGUMENT_COMMAND_MALFORMED = "ERR_ARGUMENT_COMMAND_MALFORMED"
ERR_COMMAND_FILE_NOT_FOUND = "ERR_COMMAND_FILE_NOT_FOUND"
ERR_CORE_REPO_DIRTY = 'ERR_CORE_REPO_DIRTY'
ERR_ENV_VAR_MISSING = 'ERR_ENV_VAR_MISSING'
