COLOR_GRAY_DARK = [80, 80, 80]
COLOR_RED = [240, 81, 66]
COLOR_CYAN = 'cyan'
COMMAND_SEPARATOR_ADDON = '::'
COMMAND_SEPARATOR_GROUP = '/'
COMMAND_PATTERN = '^(?:(\\w+)::)?([\\w-]+)/([\\w-]+)$'
CONFIG_SEPARATOR_DEFAULT = ' = '
FILE_REGISTRY = 'registry.json'
GITHUB_GROUP = 'wexample'
GITHUB_PROJECT = 'wex'
LOG_FILENAME = 'app.log'
LOG_MAX_DAYS = 90
PATH_GLOBALS = 'src/const/globals.py'
WEX_VERSION = '5.0.0-dev.2+build.20230314180944'
