#!/usr/bin/env bash

autocomplete() {
  # Get the current word being completed
  local CURRENT=${COMP_WORDS[${COMP_CWORD}]}
  # Get the search query, everything after the first word
  local SEARCH=("${COMP_WORDS[*]:1}")
  # Set the current position of the cursor
  local CURSOR=$((COMP_CWORD - 1))

  # Get autocomplete suggestions
  local SUGGESTIONS=""
  SUGGESTIONS=($(wex core::autocomplete/suggest -c "${CURSOR}" -s "${SEARCH[*]}"))

  # If current position is right after "::",
  # we need to empty var to allow suggestions
  if [ "${CURRENT}" == "::" ]; then
    CURRENT=""
  fi

  # The @ char, which is user for services, is used as a word separator in compgen
  if [[ ${SEARCH[0]} =~ ^@ ]] && [[ "${CURRENT}" != "@" ]]; then
    CURRENT="@${CURRENT}"
  fi

  # Generate autocomplete suggestions using compgen
  COMPREPLY=($(compgen -W "${SUGGESTIONS[*]}" -- ${CURRENT}))

  # Check for single suggestion
  if [[ "${COMPREPLY}" != "" ]] && ! [[ ${COMPREPLY[*]} =~ [\ ] ]]; then
    if [[ "${COMPREPLY[@]}" = *"/"* ]];then
      COMPREPLY+=" "
    fi
  fi
}

autocomplete
