#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root or using sudo"
    exit
fi

wex_install() {
  local WEX_GROUP
  local WEX_USER_PATH_HOME
  local WEX_BIN
  local WEX_BASHRC_PATH
  local DIR_CLI
  local WEX_DIR_ROOT
  local LISTENER_COMMAND

  WEX_GROUP=$(getent group "${SUDO_GID}" | cut -d: -f1)
  WEX_USER_PATH_HOME="/home/${SUDO_USER}/"
  WEX_BIN="/usr/local/bin/wex"

  # Check if user directory exists, create it if missing,
  # expected for .bashrc edition.
  if [ ! -d "${WEX_USER_PATH_HOME}" ]; then
    mkdir -p "${WEX_USER_PATH_HOME}"
    chown "${SUDO_USER}:${WEX_GROUP}" "${WEX_USER_PATH_HOME}"
  fi

  WEX_BASHRC_PATH=${WEX_BASHRC_PATH:-$(realpath "${WEX_USER_PATH_HOME}.bashrc")}
  touch "${WEX_BASHRC_PATH}"
  local DIR_CLI
  DIR_CLI="$(realpath "$(dirname "${BASH_SOURCE[0]}")")/"
  local WEX_DIR_ROOT
  WEX_DIR_ROOT="$(realpath "${DIR_CLI}../")/"

  local WEX_FILE_BASHRC_HANDLER="${DIR_CLI}bashrc-handler"
  local WEX_FILE_BASHRC_COMMAND=". ${WEX_FILE_BASHRC_HANDLER}"

  echo "Adding autocompletion script to ${WEX_BASHRC_PATH}..."
  echo "Bashrc handler path : ${WEX_FILE_BASHRC_COMMAND}"
  bash "${WEX_DIR_ROOT}cli/wex" default::file/append_once -f "${WEX_BASHRC_PATH}" -l "${WEX_FILE_BASHRC_COMMAND}"

  # TODO Remove or reactivate
  #      Event we are in docker, the python dependencies should be installed by apt, not here
  # echo "Installing with python..."
  # pip install "${WEX_DIR_ROOT}" -r "${WEX_DIR_ROOT}requirements.txt"

  echo "Adding symlink.."
  if [ -L ${WEX_BIN} ]; then
    rm "${WEX_BIN}"
  fi

  ln -fs "${WEX_DIR_ROOT}cli/wex" ${WEX_BIN}
  chmod -R +x ${WEX_BIN}

  echo "Running Webhook listener"
  LISTENER_COMMAND="wex core::webhook/serve -p 4242"

  # Stop any existing listeners
  pkill -f "${LISTENER_COMMAND}"
  nohup ${LISTENER_COMMAND} > "${WEX_DIR_ROOT}tmp/webhook-server.out" 2>&1 &

  wex core::logo/show
}

wex_install
