#!/usr/bin/env bash

wex_install() {
  WEX_USER=${WEX_USER:-$(whoami)}
  WEX_GROUP=${WEX_GROUP:-$(id -gn "${WEX_USER}")}
  WEX_USER_PATH_HOME="/home/${WEX_USER}/"
  WEX_BIN="/usr/local/bin/wex"

  # Check if user directory exists, create it if missing,
  # expected for .bashrc edition.
  if [ ! -d "${WEX_USER_PATH_HOME}" ]; then
    mkdir -p "${WEX_USER_PATH_HOME}"
    chown "${WEX_USER}:${WEX_GROUP}" "${WEX_USER_PATH_HOME}"
  fi

  WEX_BASHRC_PATH=${WEX_BASHRC_PATH:-$(realpath "${WEX_USER_PATH_HOME}.bashrc")}
  touch "${WEX_BASHRC_PATH}"
  local DIR_CLI
  DIR_CLI="$(realpath "$(dirname "${BASH_SOURCE[0]}")")/"
  local WEX_DIR_ROOT
  WEX_DIR_ROOT="$(realpath "${DIR_CLI}../")/"

  local WEX_FILE_BASHRC_HANDLER="${DIR_CLI}bashrc-handler"
  local WEX_FILE_BASHRC_COMMAND=". ${WEX_FILE_BASHRC_HANDLER}"

  echo "Adding autocompletion script to ${WEX_BASHRC_PATH}..."
  echo "Bashrc handler path : ${WEX_FILE_BASHRC_COMMAND}"
  bash "${WEX_DIR_ROOT}cli/wex" default::file/append_once -f "${WEX_BASHRC_PATH}" -l "${WEX_FILE_BASHRC_COMMAND}"

  echo "Installing with python..."
  pip install "${WEX_DIR_ROOT}" -r "${WEX_DIR_ROOT}requirements.txt"

  echo "Adding symlink.."
  if [ -L ${WEX_BIN} ]; then
    rm "${WEX_BIN}"
  fi

  ln -fs "${WEX_DIR_ROOT}cli/wex" ${WEX_BIN}
  chmod -R +x ${WEX_BIN}

  echo "Running Webhook listener"
  LISTENER_COMMAND="wex core::webhook/serve -p 4242"
  LOG_FILE="${WEX_DIR_ROOT}tmp/webhook-server.out"
  MAX_LINES=1000

  # Stop any existing listeners
  pkill -f "${LISTENER_COMMAND}"
  nohup ${LISTENER_COMMAND} > "${WEX_DIR_ROOT}tmp/webhook-server.out" 2>&1 &
}

wex_install
