#!/usr/bin/env bash

# Trigger error on failing
set -e

WEX_DIR_CLI="$(realpath "$(dirname "${BASH_SOURCE[0]}")")/"
WEX_DIR_ROOT="$(realpath "${WEX_DIR_CLI}../")/"

echo "Installing python requirements..."
pip install "${WEX_DIR_ROOT}" -r "${WEX_DIR_ROOT}requirements.txt"

echo "Installing wex"
. "${WEX_DIR_CLI}wex" core::core/install

echo "Reload bashrc changes..."
# shellcheck disable=SC1090
. ~/.bashrc