#!/usr/bin/env bash

WEX_DIR_ROOT="$(dirname "${BASH_SOURCE[0]}")/../"

. "${WEX_DIR_ROOT}.wex/.env"

PREFIX=${APP_ENV^^}
# We are in a docker container.
if [ -e /.dockerenv ]; then
  COLOR="\033[1;90m"
  PREFIX="~${PREFIX,,}>"
else
  if [ "${APP_ENV}" == "local" ]; then
    COLOR="\033[0;32m"
  elif [ "${APP_ENV}" == "dev" ]; then
    COLOR="\033[0;33m"
  else
    COLOR="\033[0;31m"
  fi

  PREFIX="[${PREFIX,,}]"
fi

export PS1="\[${COLOR}\]${PREFIX}\[\033[0m\] \\u:\\W\\$ "
