#!/usr/bin/env bash

# Find current file directory
# supporting symlinks
WEX_DIR_CLI="$(realpath "$(dirname "$(readlink -f ${BASH_SOURCE[0]})")")/"

. "${WEX_DIR_CLI}/_init.sh"
. "${WEX_DIR_CLI}/_init_sudo.sh"

# Remove container if exists
docker rm -f wex 2>/dev/null

sudo bash "${WEX_DIR_CLI}wex" core::core/uninstall
