#!/bin/bash

# This script serves as the entry point for the 'wex' application when installed via an APT package.
# It attempts to execute the 'wex' file from the absolute path '/usr/lib/wex/cli/'.
/usr/lib/wex/cli/wex "$@"

