dependencies:
  - postgres
main: true
docker:
  network_name: wex_net_ai
structure:
  schema:
    ollama:
      permissions:
        mode: 755
        recursive: true
      should_exist: true
      type: dir