services:
  jenkins:
    extends:
        file: ${SERVICE_DEFAULT_YML_ENV}
        service: default
    container_name: '${CONTEXT_NAME}_jenkins'
    image: 'jenkins/jenkins:${JENKINS_VERSION}'
    ports:
      - "50000:50000"
    environment:
      - VIRTUAL_HOST=${CONTEXT_DOMAINS}
      - VIRTUAL_PORT=8080
    volumes:
      - ${CONTEXT_DIR}config:/jenkins_config
      - ${CONTEXT_DIR}home:/var/jenkins_home
