services:
    mysql:
        container_name: '${RUNTIME_NAME}_mysql'
        image: mysql:8.1
        environment:
            - MYSQL_DATABASE=${SERVICE_MYSQL_NAME}
            - MYSQL_PASSWORD=${SERVICE_MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${SERVICE_MYSQL_PASSWORD}
            - MYSQL_TCP_PORT=${SERVICE_MYSQL_PORT}
        volumes:
            - ${RUNTIME_PATH_APP_ENV}mysql/data:/var/lib/mysql
            - ${RUNTIME_PATH_APP_ENV}mysql/dumps:/var/www/dumps
            - ${RUNTIME_PATH_APP_ENV}tmp/mysql.cnf:/tmp/mysql.cnf
        extends:
            file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
            service: default