services:
  n8n:
    container_name: ${CONTEXT_NAME}_n8n
    image: n8nio/n8n:${N8N_VERSION}
    ports:
      - 5678:5678
    environment:
      - VIRTUAL_HOST=${CONTEXT_DOMAINS}
      - VIRTUAL_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${DOMAIN_MAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_TUNNEL_URL=https://${DOMAIN_MAIN}/
      - GENERIC_TIMEZONE=Europe/Paris
    volumes:
      # Minimal env files.
      - ${CONTEXT_DIR}n8n:/home/node/.n8n
    extends:
      file: ${SERVICE_DEFAULT_YML_ENV}
      service: default
