

deploy:apt:build:
  stage: deploy
  image: gitlab-docker.wexample.com/wexample-public/docker/wex:build
  only:
    - master
  script:
    - BUILD_VERSION=$(cat version.txt)
    # Create build folder outside shared volume
    - mkdir -p /var/tmp/build
    # Create a copy of current git repo
    - cp -r .git /var/tmp/build
    # Go to build folder
    - cd /var/tmp/build
    # Checkout build branch
    - git fetch && git checkout build
    # Create link to source
    - ln -s ${CI_PROJECT_DIR} source
    # Build
    - sudo python3 /var/tmp/build/script/build.py -n wex -gid ${CI_PROJECT_ID} -gtk ${WEX_BUILD_TOKEN} -v ${BUILD_VERSION}

deploy:apt:publish:
  stage: deploy
  image: curlimages/curl
  only:
    - master
  needs:
    - deploy:apt:build
  script:
    - BUILD_VERSION=$(cat version.txt)
    # Ask apt repo to publish release
    - curl "http://wexample.com:46017/webhook/app/prod/wex-apt-repo/apt/publish?p=${CI_PROJECT_ID}&v=${BUILD_VERSION}"
