services:
  wex_dev:
    container_name: wex_standalone
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    image: gitlab-docker.wexample.com/wexample-public/docker/wex:dev
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      # Work dir
      - ../../:/opt/wex/
      # TODO Remove on RC
      # Use an updated .wex folder structure for internal dev an testing.
      - ../../.wex-5-dev:/opt/wex/.wex
      # Tests
      - ../../tmp/tests-standalone/wex-proxy:/opt/wex-proxy
      - ../../tmp/tests-standalone/my-app:/var/www/local/my-app
      # Docker sharing
      - /var/run/docker.sock:/var/run/docker.sock

