services:
  jenkins:
    extends:
        file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
        service: default
    container_name: '${RUNTIME_NAME}_jenkins'
    image: 'jenkins/jenkins:2.60.3'
    ports:
      - "50000:50000"
    environment:
      - VIRTUAL_HOST=${RUNTIME_DOMAINS_STRING}
      - VIRTUAL_PORT=8080
    volumes:
      - ${RUNTIME_PATH_APP}config:/jenkins_config
      - ${RUNTIME_PATH_APP}home:/var/jenkins_home
