services:
    grafana:
      container_name: ${RUNTIME_NAME}_grafana
      image: grafana/grafana:${GRAFANA_VERSION}
      volumes:
        - ${RUNTIME_PATH_APP}grafana:/var/lib/grafana
        - ${RUNTIME_PATH_APP}provisioning:/etc/grafana/provisioning/
      environment:
        - VIRTUAL_HOST=${RUNTIME_DOMAINS}
        - VIRTUAL_PORT=80
      extends:
          file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
          service: default