services:
    onlyoffice:
        container_name: '${RUNTIME_NAME}_onlyoffice'
        image: 'onlyoffice/documentserver:${ONLYOFFICE_DOCUMENT_SERVER_VERSION}'
        ports:
            # MPP-compatible instant messaging client (for ONLYOFFICE Talk correct work)
            - "5222:5222"
        environment:
            - VIRTUAL_HOST=${CONTEXT_DOMAINS}
            - VIRTUAL_PORT=80
        volumes:
            - ${PATH_APP}logs:/var/log/onlyoffice
            - ${PATH_APP}data:/var/www/onlyoffice/Data
        extends:
            file: ${SERVICE_DEFAULT_YML_ENV}
            service: default
