services:
    onlyoffice:
        container_name: '${RUNTIME_NAME}_onlyoffice'
        image: 'onlyoffice/documentserver:7.4.1'
        ports:
            # MPP-compatible instant messaging client (for ONLYOFFICE Talk correct work)
            - "5222:5222"
        environment:
            - VIRTUAL_HOST=${RUNTIME_DOMAINS_STRING}
            - VIRTUAL_PORT=80
        volumes:
            - ${RUNTIME_PATH_APP}logs:/var/log/onlyoffice
            - ${RUNTIME_PATH_APP}data:/var/www/onlyoffice/Data
        extends:
            file: ${RUNTIME_SERVICE_DEFAULT_YML_ENV}
            service: default
