git:
  publication_strategy: branch_merge
global:
  description: Runs infrastructure and Docker-backed apps from a single command line, resolving addon-provided commands under one shared grammar
  name: wex
  version: 6.0.130
libraries:
  - ${PROGRAM_PUBLICATION_SOURCE_LIBRARY_PATH}
wex:
  migration: 5
  version: 6.0.136
