FROM odoo:11.0

# TODO ISSUE WITH SHARE DATA VOLUME AND USER WRITE ACCESS (need odoo user to be owner)

#USER root

#RUN chown -R odoo:odoo /var/lib/odoo

#COPY ./entrypoint-odoo11.sh /

#RUN chmod +x ./entrypoint-odoo11.sh

#ENTRYPOINT ["/entrypoint-odoo11.sh"]
