.\" Manpage for wex.
.\" Contact weeger <contact@wexample.com> to correct errors or typos.

.TH wex 1 "24 Mar 2023" "5.0.0~beta.2" "wex man page"

.SH NAME
wex - A single entrypoint to execute custom scripts, and run Docker application on several environments.

.SH SYNOPSIS
.B wex
[\fIOPTION\fR]...

.SH DESCRIPTION
The \fIwex\fR command allows to execute custom scripts, and run Docker application on several environments.

.SH OPTIONS
The following options are available:

.TP
\fB--help\fR
Show help message and exit.

.SH AUTHOR
This manual page was written by weeger <contact@wexample.com> for the Debian system (but may be used by others).

.SH COPYRIGHT
Copyright \(co 2023 weeger. This manual page is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License (CC BY-SA 4.0).

.SH SEE ALSO
The full documentation for \fIwex\fR is maintained as a README file in the project repository on Github (https://github.com/myusername/wex).
