#!/usr/bin/env bash

proxyConfig() {

  export WEX_DOCKER_MACHINE_IP=$(wex docker/ip)
  export WEX_WEXAMPLE_DIR_TMP=${WEX_WEXAMPLE_DIR_TMP}
  export WEX_IMAGES_VERSION=$(wex wex/version)
  export WEX_SERVER_PORT_PUBLIC=${WEX_SERVER_PORT_PUBLIC}

  local CONFIG=''
  CONFIG+="\nWEX_DOCKER_MACHINE_IP="${WEX_DOCKER_MACHINE_IP}
  CONFIG+="\nWEX_WEXAMPLE_DIR_TMP="${WEX_WEXAMPLE_DIR_TMP}
  CONFIG+="\nWEX_IMAGES_VERSION="${WEX_IMAGES_VERSION}
  CONFIG+="\nWEX_SERVER_PORT_PUBLIC="${WEX_SERVER_PORT_PUBLIC}

  echo ${CONFIG}
}
