ASSISTANT_MENU_ACTION_CHANGE_LANGUAGE = "CHANGE_LANGUAGE"
ASSISTANT_MENU_ACTION_CHANGE_DEFAULT_MODEL = "CHANGE_MODEL"
ASSISTANT_MENU_ACTION_CHANGE_PERSONALITY = "CHANGE_PERSONALITY"
ASSISTANT_MENU_ACTION_THEME = "THEME"
ASSISTANT_MENU_ACTION_EXIT = "EXIT"
ASSISTANT_MENU_ACTION_CHAT = "TALK"

ASSISTANT_MENU_ACTIONS_TRANSLATIONS = {
    ASSISTANT_MENU_ACTION_CHAT: "Back to chat",
    ASSISTANT_MENU_ACTION_THEME: "Change colors theme",
    ASSISTANT_MENU_ACTION_CHANGE_DEFAULT_MODEL: "Change default model",
    ASSISTANT_MENU_ACTION_CHANGE_PERSONALITY: "Change personality",
    ASSISTANT_MENU_ACTION_CHANGE_LANGUAGE: "Change language",
    ASSISTANT_MENU_ACTION_EXIT: "Exit",
}

AI_COMMAND_PREFIX = "/"
AI_FUNCTION_DISPLAY_A_CUCUMBER = "display_a_cucumber"

ASSISTANT_COMMAND_EXIT = "exit"
ASSISTANT_COMMAND_MENU = "menu"

ASSISTANT_DEFAULT_COMMANDS = {
    ASSISTANT_COMMAND_EXIT: "Quit",
    ASSISTANT_COMMAND_MENU: "Show menu",
}
