AI_IDENTITY_DEFAULT = "default"
AI_IDENTITY_CODE_FILE_PATCHER = "code_file_patcher"
AI_IDENTITY_COMMAND_SELECTOR = "command_selector"
AI_IDENTITY_FILE_INSPECTION = "file_inspection"
AI_IDENTITY_GIT_PATCH_CREATOR = "patch_creator"
AI_IDENTITY_TOOLS_AGENT = "tools_agent"

CHAT_MENU_ACTION_CHANGE_DEFAULT_MODEL = "CHANGE_MODEL"
CHAT_MENU_ACTION_THEME = "THEME"
CHAT_MENU_ACTION_EXIT = "EXIT"
CHAT_MENU_ACTION_CHAT = "TALK"

CHAT_MENU_ACTIONS_TRANSLATIONS = {
    CHAT_MENU_ACTION_CHAT: "Back to chat",
    CHAT_MENU_ACTION_THEME: "Change colors theme",
    CHAT_MENU_ACTION_CHANGE_DEFAULT_MODEL: "Change default model",
    CHAT_MENU_ACTION_EXIT: "Exit",
}

AI_COMMAND_PREFIX = "/"
AI_FUNCTION_DISPLAY_A_CUCUMBER = "display_a_cucumber"

ASSISTANT_COMMAND_EXIT = "exit"
ASSISTANT_COMMAND_FUNCTION = "function"
ASSISTANT_COMMAND_HELP = "help"
ASSISTANT_COMMAND_MENU = "menu"
ASSISTANT_COMMAND_TOOL = "tool"

ASSISTANT_DEFAULT_COMMANDS = {
    ASSISTANT_COMMAND_FUNCTION: "Ask to guess and run function (beta).",
    ASSISTANT_COMMAND_EXIT: "quit.",
    ASSISTANT_COMMAND_HELP: "display this message again.",
    ASSISTANT_COMMAND_MENU: "show menu.",
    ASSISTANT_COMMAND_TOOL: "Ask to run a tool (beta).",
}
