CHAT_MENU_ACTION_CHANGE_LANGUAGE = "CHANGE_LANGUAGE"
CHAT_MENU_ACTION_CHANGE_DEFAULT_MODEL = "CHANGE_MODEL"
CHAT_MENU_ACTION_CHANGE_PERSONALITY = "CHANGE_PERSONALITY"
CHAT_MENU_ACTION_THEME = "THEME"
CHAT_MENU_ACTION_EXIT = "EXIT"
CHAT_MENU_ACTION_CHAT = "TALK"

CHAT_MENU_ACTIONS_TRANSLATIONS = {
    CHAT_MENU_ACTION_CHAT: "Back to chat",
    CHAT_MENU_ACTION_THEME: "Change colors theme",
    CHAT_MENU_ACTION_CHANGE_DEFAULT_MODEL: "Change default model",
    CHAT_MENU_ACTION_CHANGE_PERSONALITY: "Change personality",
    CHAT_MENU_ACTION_CHANGE_LANGUAGE: "Change language",
    CHAT_MENU_ACTION_EXIT: "Exit",
}

AI_COMMAND_PREFIX = "/"
AI_FUNCTION_DISPLAY_A_CUCUMBER = "display_a_cucumber"

ASSISTANT_COMMAND_EXIT = "exit"
ASSISTANT_COMMAND_MENU = "menu"

ASSISTANT_DEFAULT_COMMANDS = {
    ASSISTANT_COMMAND_EXIT: "Quit",
    ASSISTANT_COMMAND_MENU: "Show menu",
}
