AI_IDENTITY_DEFAULT = "default"
AI_IDENTITY_CODE_FILE_PATCHER = "code_file_patcher"
AI_IDENTITY_COMMAND_SELECTOR = "command_selector"
AI_IDENTITY_FILE_INSPECTION = "file_inspection"
AI_IDENTITY_TOOLS_AGENT = "tools_agent"
