services:
  nextcloud:
    extends:
      file: ${RUNTIME_SERVICE_NEXTCLOUD_YML_ENV}
      service: nextcloud
    # Should be defined at least for first installation.
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=supersecretpassword