#!/bin/bash

# Init only once.
if [[ $(type -t wex-exec) != "function" ]]; then
  . /opt/wex/includes/globals.sh
  . /opt/wex/includes/function/wex-exec.sh
fi

# Execute function with same arguments.
wex-exec "$@"
