#!/bin/bash

# Init only once.
if [[ $(type -t wex-exec) != "function" ]]; then
  . /opt/wex/includes/globals.sh
  . /opt/wex/includes/function/wex-exec.sh
  # Empty trace file.
  echo "" >"${WEX_FILE_TRACE}"
  # Create require files if missing.
  touch "${WEX_FILE_ALL_SCRIPTS_PATHS}"
  # Avaoid access errors by non sudo users.
  chmod 777 "${WEX_FILE_TRACE}"
  chmod 777 "${WEX_FILE_ALL_SCRIPTS}"
  chmod 777 "${WEX_FILE_ALL_SCRIPTS_PATHS}"
fi

# Execute function with same arguments.
wex-exec "$@"
