services:
  n8n:
    environment:
      # Should use the default https port to match reverse proxy default config,
      # instead the default 5678 port.
      - N8N_PORT=443
      - LETSENCRYPT_HOST=${RUNTIME_DOMAINS_STRING}
      - LETSENCRYPT_EMAIL=${RUNTIME_EMAIL}
    ports:
    - 5678:443
